### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by HugoGiraudel** [SassDoc/sassdoc-theme-default#47]

**Comment by valeriangalliat** [comment]
From Slack conversation, we need something like this:

```js
this.push(function () {
  return swig(path.resolve(__dirname, 'views/index.html.swig'), this.ctx)
    .then(minify)
    .then(writeFile(resolve(this.dest, 'index.html')));
}.bind(this));
```
In a future Themeleon version it could be:

```js
this.push(function (resolve, reject) {
  return swig(path.resolve(__dirname, 'views/index.html.swig'), this.ctx, function (err, html) {
    if (err) return reject(err);

    fs.writeFile(path.resolve(this.dest, 'index.html'), minify(html), function (err) {
      if (err) return reject(err);
    });
}.bind(this));
```

And now I write the second example, I'm not sure it's really a good thing to abstract the promises away this way… @FWeinb?

**Comment by FWeinb** [comment]
You never do a `resolve`? Looks not good but I think I could live with that.

**Comment by valeriangalliat** [comment]
> You never do a resolve?

Fixed the example.

> Looks not good but I think I could live with that.

Okay… because if I implement this in SassDoc I will for sure include a `denodeify` function and do it the promise way.

**Comment by HugoGiraudel** [comment]
What is the status on this and who takes it?

**Comment by valeriangalliat** [comment]
f99fd17472eb4ec662279bcf324ff25a96de364e
