### ISSUE TITLE
Issues with `@alias` 

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc-theme-default#52]
Added some tests of `@alias` after reviewing the coverage results, as for SassDoc/sassdoc#335

Found that:
- "Refer to" is broken.
- When an aliased item is not found, SassDoc warns accordingly, but should we still display the "alias for" on the title right hand ?

![screen shot 2015-01-26 at 12 01 32](https://cloud.githubusercontent.com/assets/335467/5898867/33fa93d6-a554-11e4-8116-67eee2a12150.png)

**Comment by HugoGiraudel** [comment]
> When an aliased item is not found, SassDoc warns accordingly, but should we still display the "alias for" on the title right hand ?

There is no way for the theme to know that an item does not exist.

**Comment by HugoGiraudel** [comment]
First issue fixed: https://github.com/SassDoc/sassdoc-theme-default/commit/398f80b21c93666e619d653e564ad8ac8d9fb6b1.

**Comment by FWeinb** [comment]
We should remove the item when reporting. See https://github.com/SassDoc/sassdoc/blob/master/src/annotation/annotations/alias.js#L31
