### ISSUE TITLE
Add ability to describe an introduction text

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sassdoc-theme-default#66]
Following of SassDoc/sassdoc#256

* Add a description (or fullDescription or whatever) key to the configuration
* If it is a string, parses it as Markdown
* if it is a path, get content and parses it as Markdown

**Comment by HugoGiraudel** [comment]
Who takes it?

**Comment by pascalduez** [comment]
I'm thinking this could (again) be a task for `sassdoc-extras`. The loading and parsing logic.
